description: Audio resampling library for ESP32 devices
files:
  exclude:
  - .clang-format
  - .gitignore
  - library.json
repository: git://github.com/esphome-libs/esp-audio-libs.git
repository_info:
  commit_sha: c19599c47607029c42b332b066da4e5cd7fe0c4a
  path: .
url: https://github.com/esphome/esp-audio-libs
version: 3.0.0
