; PlatformIO configuration for FLAC decode benchmark
;
; Build and upload:
;   pio run -e esp32 -t upload -t monitor
;   pio run -e esp32s3 -t upload -t monitor
;   pio run -e esp32s3_24bit -t upload -t monitor
;   pio run -e esp32p4 -t upload -t monitor
;   pio run -e esp32p4_24bit -t upload -t monitor

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
framework = espidf
monitor_speed = 115200
lib_ignore = micro-flac
board_build.partitions = partitions_16mb.csv

[env:esp32]
board = esp32dev
board_build.partitions = partitions_4mb.csv
board_build.sdkconfig_defaults = sdkconfig.defaults, sdkconfig.defaults.esp32

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
upload_protocol = esp-builtin
board_build.sdkconfig_defaults = sdkconfig.defaults, sdkconfig.defaults.esp32s3

[env:esp32s3_24bit]
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
upload_protocol = esp-builtin
board_build.sdkconfig_defaults = sdkconfig.defaults, sdkconfig.defaults.esp32s3
build_flags = -DBENCHMARK_INCLUDE_24BIT

[env:esp32p4]
board = esp32-p4-evboard
board_build.flash_size = 16MB
board_build.sdkconfig_defaults = sdkconfig.defaults, sdkconfig.defaults.esp32p4

[env:esp32p4_24bit]
board = esp32-p4-evboard
board_build.flash_size = 16MB
board_build.sdkconfig_defaults = sdkconfig.defaults, sdkconfig.defaults.esp32p4
build_flags = -DBENCHMARK_INCLUDE_24BIT
