#pragma once
#include "esphome/core/macros.h"
#define API_MAX_SEND_QUEUE 8
#define BLUETOOTH_PROXY_ADVERTISEMENT_BATCH_SIZE 16
#define BLUETOOTH_PROXY_MAX_CONNECTIONS 3
#define CONTROLLER_REGISTRY_MAX 1
#define ESPHOME_BOARD "esp32-s3-devkitc-1"
#define ESPHOME_COMPONENT_COUNT 73
#define ESPHOME_ENTITY_BINARY_SENSOR_COUNT 2
#define ESPHOME_ENTITY_BUTTON_COUNT 4
#define ESPHOME_ENTITY_LIGHT_COUNT 1
#define ESPHOME_ENTITY_MEDIA_PLAYER_COUNT 1
#define ESPHOME_ENTITY_SELECT_COUNT 1
#define ESPHOME_ENTITY_SENSOR_COUNT 5
#define ESPHOME_ENTITY_SWITCH_COUNT 3
#define ESPHOME_ENTITY_TEXT_SENSOR_COUNT 6
#define ESPHOME_ESP32_BLE_BLE_STATUS_EVENT_HANDLER_COUNT 1
#define ESPHOME_ESP32_BLE_GAP_EVENT_HANDLER_COUNT 1
#define ESPHOME_ESP32_BLE_GAP_SCAN_EVENT_HANDLER_COUNT 1
#define ESPHOME_ESP32_BLE_GATTC_EVENT_HANDLER_COUNT 1
#define ESPHOME_ESP32_BLE_TRACKER_CLIENT_COUNT 3
#define ESPHOME_ESP32_BLE_TRACKER_LISTENER_COUNT 1
#define ESPHOME_LOGGER_TX_BUFFER_SIZE 512
#define ESPHOME_LOG_MAX_LISTENERS 1
#define ESPHOME_LOOP_TASK_STACK_SIZE 8192
#define ESPHOME_NAME_ADD_MAC_SUFFIX
#define ESPHOME_PROJECT_NAME "salnajjar.waveshare_esp32_s3_smart_86_box"
#define ESPHOME_PROJECT_VERSION "b19-20260427-200111"
#define ESPHOME_PROJECT_VERSION_30 "b19-20260427-200111"
#define ESPHOME_TASK_LOG_BUFFER_SIZE 768
#define ESPHOME_THREAD_MULTI_ATOMICS
#define ESPHOME_VARIANT "ESP32-S3"
#define ESPHOME_WIFI_CONNECT_STATE_LISTENERS 1
#define MDNS_SERVICE_COUNT 1
#define USE_API
#define USE_API_CLIENT_CONNECTED_TRIGGER
#define USE_API_CLIENT_DISCONNECTED_TRIGGER
#define USE_API_PLAINTEXT
#define USE_AUDIO_ADC
#define USE_AUDIO_DAC
#define USE_AUDIO_FLAC_SUPPORT
#define USE_BINARY_SENSOR
#define USE_BLUETOOTH_PROXY
#define USE_BUTTON
#define USE_CAPTIVE_PORTAL
#define USE_CAPTIVE_PORTAL_GZIP
#define USE_CONTROLLER_REGISTRY
#define USE_DEBUG
#define USE_DISPLAY
#define USE_ENTITY_DEVICE_CLASS
#define USE_ENTITY_ICON
#define USE_ENTITY_UNIT_OF_MEASUREMENT
#define USE_ESP32_BLE
#define USE_ESP32_BLE_CLIENT
#define USE_ESP32_BLE_MAX_CONNECTIONS 3
#define USE_ESP32_BLE_SOFTWARE_COEXISTENCE
#define USE_ESP32_CRASH_HANDLER
#define USE_ESPHOME_TASK_LOG_BUFFER
#define USE_ESP_IDF_VERSION_CODE VERSION_CODE(5, 5, 4)
#define USE_FONT
#define USE_HOMEASSISTANT_TIME
#define USE_I2C
#define USE_IMAGE
#define USE_LIGHT
#define USE_LIGHT_GAMMA_LUT
#define USE_LOGGER
#define USE_LOGGER_UART_SELECTION_USB_SERIAL_JTAG
#define USE_LOGGER_USB_CDC
#define USE_LOGGER_USB_SERIAL_JTAG
#define USE_LOG_LISTENERS
#define USE_MD5
#define USE_MDNS
#define USE_MEDIA_PLAYER
#define USE_MICROPHONE
#define USE_MICRO_WAKE_WORD
#define USE_NATIVE_64BIT_TIME
#define USE_NETWORK
#define USE_NETWORK_IPV6 false
#define USE_OTA
#define USE_OTA_ROLLBACK
#define USE_OTA_STATE_LISTENER
#define USE_OTA_VERSION 2
#define USE_OUTPUT
#define USE_PSRAM
#define USE_SELECT
#define USE_SENSOR
#define USE_SHA256
#define USE_SOCKET_IMPL_BSD_SOCKETS
#define USE_SPEAKER
#define USE_SPI
#define USE_SWITCH
#define USE_TEXT_SENSOR
#define USE_TIME
#define USE_TIME_TIMEZONE
#define USE_VOICE_ASSISTANT
#define USE_WEBSERVER_OTA
#define USE_WIFI
#define USE_WIFI_AP
#define USE_WIFI_CONNECT_STATE_LISTENERS
#define USE_WIFI_CONNECT_TRIGGER
#define USE_WIFI_DISCONNECT_TRIGGER
#define WEB_SERVER_DEFAULT_HEADERS_COUNT 1
